name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: npm install
        run: npm ci
      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - name: Set up cargo binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | sh
      - name: Set up Dioxus
        run: cargo binstall dioxus-cli@0.6.1
      - name: Dioxus build
        run: dx build --verbose
      - name: Upload build artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/dx/klsyn-dioxus/debug/web/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
